packages:
  - packages/*

catalog:
  '@biomejs/biome': 2.5.6
  '@changesets/cli': ^2.29.8
  '@iconify/json': ^2.2.417
  '@types/hast': ^3.0.4
  '@types/node': 24.12.0
  es-toolkit: 1.45.1
  lint-staged: ^16.2.7
  rollup-plugin-visualizer: ^6.0.5
  simple-git-hooks: ^2.13.1
  turbo: 2.9.3
  type-fest: 5.5.0
  typescript: 5.9.3
  ultracite: 7.0.10
  unplugin-icons: ^23.0.0
  vite-plugin-compression2: ^2.4.0

catalogMode: strict

catalogs:
  analyzer:
    '@napi-rs/cli': 3.8.1
  build:
    tsdown: 0.21.7
    tsx: 4.21.0
  cli:
    chokidar: 5.0.0
    destr: 2.0.5
    get-port-please: 3.2.0
    gunshi: 0.29.3
    h3: 2.0.1-rc.15
    mrmime: 2.0.1
    open: 11.0.0
    yocto-spinner: 1.1.0
  test:
    '@solidjs/testing-library': 0.8.10
    '@testing-library/jest-dom': 6.9.1
    '@testing-library/user-event': 14.6.1
    '@vitest/browser-playwright': 4.1.10
    '@vitest/ui': 4.1.10
    fishery: 2.4.0
    jsdom: 27.4.0
    playwright: 1.59.1
    vitest: 4.1.10
  ui:
    '@ark-ui/solid': 5.37.1
    '@shikijs/core': 3.23.0
    '@shikijs/engine-javascript': 3.23.0
    '@shikijs/langs-precompiled': 3.23.0
    '@shikijs/themes': 3.23.0
    '@shikijs/types': 3.23.0
    '@solid-primitives/scheduled': 1.5.3
    '@solidjs/router': 0.16.3
    '@tailwindcss/vite': 4.2.2
    class-variance-authority: 0.7.1
    solid-js: 1.9.14
    tailwindcss: 4.2.2
    vite: 7.3.6
    vite-plugin-solid: 2.11.14
