packages:
   - packages/*

catalog:
   "@biomejs/biome": 2.3.3
   "@types/node": 24.8.0
   es-toolkit: 1.41.0
   solid-motionone: ^1.0.4
   turbo: 2.6.0
   type-fest: 5.2.0
   typescript: 5.9.3
   ultracite: 6.2.1
   valibot: 1.1.0

catalogMode: strict

catalogs:
   analyzer:
      "@napi-rs/cli": 3.3.1
   build:
      tsdown: 0.15.12
      tsx: 4.20.6
   cli:
      consola: 3.4.2
      cuin-analyzer: 0.0.2-fix-14
      get-port-please: 3.2.0
      gunshi: 0.26.3
      h3: 2.0.1-rc.5
      mrmime: 2.0.1
      open: 10.2.0
   test:
      "@solidjs/testing-library": 0.8.10
      "@testing-library/jest-dom": 6.9.1
      "@testing-library/user-event": 14.6.1
      "@vitest/browser-playwright": 4.0.6
      "@vitest/ui": 4.0.6
      jsdom: 27.1.0
      playwright: 1.56.1
      vitest: 4.0.6
   ui:
      "@ark-ui/solid": 5.27.1
      "@corvu/resizable": 0.2.5
      "@shikijs/core": 3.14.0
      "@shikijs/engine-javascript": 3.14.0
      "@shikijs/langs": 3.14.0
      "@shikijs/langs-precompiled": 3.14.0
      "@shikijs/themes": 3.14.0
      "@shikijs/types": 3.14.0
      "@solid-primitives/scheduled": 1.5.2
      "@solidjs/router": 0.15.0
      "@solidjs/start": 1.1.0
      "@tailwindcss/postcss": 4.0.0
      "@tailwindcss/vite": 4.0.7
      class-variance-authority: 0.7.1
      shiki: 3.14.0
      solid-icons: 1.1.0
      solid-js: 1.9.10
      tailwind-merge: 3.3.1
      tailwindcss: 4.0.7
      vinxi: 0.5.7
      vite-plugin-solid: 2.11.10
