name: autofix.ci

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  changes:
    name: Detect Changes
    runs-on: ubuntu-latest
    permissions:
      pull-requests: read
    outputs:
      autofix: ${{ steps.filter.outputs.autofix }}
    steps:
      - uses: actions/checkout@v4
      - uses: dorny/paths-filter@v3
        id: filter
        with:
          filters: |
            autofix:
              - ".github/workflows/autofix.yml"
              - "packages/cli/**"
              - "packages/ui/**"
              - "packages/schema/**"
              - "package.json"
              - "pnpm-lock.yaml"
              - "pnpm-workspace.yaml"

  autofix:
    name: autofix.ci
    needs: changes
    if: needs.changes.outputs.autofix == 'true'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
      - uses: actions/setup-node@v4
        with:
          node-version-file: .node-version
          cache: pnpm
      - run: pnpm install --frozen-lockfile
      - run: pnpm fix
      - uses: autofix-ci/action@v1
